name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run frontend sanity check
      run: echo Frontend sanity check running!
    - name: Run npm ci
      run: npm ci
      working-directory: frontend
    - name: Run test case
      run: npm run test:unit
      working-directory: frontend
    - name: Run backend sanity check
      run: echo Backend sanity check running!
    - name: Run npm ci
      run: npm ci
      working-directory: backend
    - name: Run test case
      run: npm run test
      working-directory: backend
